**/.git
**/.gitignore
**/.vscode
**/.azure-pipelines

**/bin
**/obj

**/tests
**/docs
**/infra
tools/local-postgres

**/*.md
**/*.env
**/*.user
**/*.suo
**/*.pfx
**/*.key

docker-compose.yml
Dockerfile
.dockerignore
LICENSE
*.slnx
